version: 2.1
workflows:
  main:
    jobs:
      - unit:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - build-docs:
          filters:
            branches:
              ignore:
                - gh-pages
            tags:
              only: /.*/
      - deploy-docs:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
          requires:
            - unit
            - build-docs

job-references:
  env: &env
    docker:
      - image: julia:latest

jobs:
  unit:
    <<: *env
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout
      - run:
          name: Run Tests
          command: julia --project --code-coverage=user test/runtests.jl
      - run:
          name: Upload Coverage Results
          command: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  build-docs:
    <<: *env
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout
      - run:
          name: Build documentation
          command: |
            julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));Pkg.instantiate()'
            julia --project=docs/ docs/make.jl
      - persist_to_workspace:
          root: docs/build
          paths:
            - "*"
      - store_artifacts:
          path: docs/build
  deploy-docs:
    <<: *env
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Deploy documentation to GitHub pages
          command: |
            julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));Pkg.instantiate()'
            julia --project=docs/ docs/deploy.jl
