site_name:        ThreadedMap.jl
repo_url:         https://github.com/GenaBitu/ThreadedMap.jl
site_description: Threaded map in Julia
site_author:      Marek Dedic

theme: material

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - assets/mathjaxhelper.js

markdown_extensions:
    - extra
    - tables
    - fenced_code

docs_dir: 'build'

pages:
    - Home: index.md
    - Reference:
        - foreach(): foreach.md
        - map(): map.md
        - reduce(): reduce.md
        - mapreduce(): mapreduce.md
        - mapfoldl() and mapfoldr(): mapfold.md
